name: PR Comment
on: pull_request

jobs:
  pr_comment:
    name: PR Comment
    runs-on: ubuntu-latest
    steps: 
      - uses: kizitorashiro/hello-ts-action@v1.0.1
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Nice PR!
